name = "blog-frontend"
main = ".open-next/worker.js"
compatibility_date = "2025-10-27"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.production]
vars = { NODE_ENV = "production" }
